### PR TITLE
#159 sensor status types

### LINKED ISSUE #159: SensorStatus typings are incorrect
**Describe the bug**
The `SensorStatusManager` typings are incorrect which is propagated through the slice and rest of the app!

https://github.com/openmsupply/msupply-cold-chain/blob/develop/src/features/SensorStatus/SensorStatusManager.ts

### PR DESCRIPTION
**Pull request by joshxg**
Fixes #159 

Maaaybe this is ugly and silly. I'm not sure. I think it's good to try and have the keys of the query match a typed result, I guess!

This is changing and tidying the query as well as the result to what is actually being used currently.

The other change to the query is to allow passing in a different filter for sensors. I plan to do another PR which will allow me to pass in a filter for just the active sensors, and then we can hydrate the app and get all the status' at once to hopefully reduce load time a little

### CODE REVIEW

File: src/common/types/common.d.ts [hunk 1]
```diff
@@ -5,3 +5,5 @@ export declare type PreparedAction<T> = {
 export declare type MacAddress = string;
 
 export declare type UnixTime = number;
+
+export type ById<SomeTypeSortedById> = Record<string, SomeTypeSortedById>;
```
Comment (joshxg) [inline src/common/types/common.d.ts:9]: offroad. Potentially also a silly type

File: src/features/Chart/ChartSlice.ts [hunk 2]
```diff
@@ -116,21 +116,7 @@ const isLoading = ({ chart: { listLoadingById } }: RootState, { id }: { id: stri
...
-): { from: number; to: number } => {
-  // TODO: Fix types
-  // eslint-disable-next-line @typescript-eslint/no-explicit-any
-  const { byId } = sensorStatus as Record<string, any>;
-  const { [id]: status } = byId;
-  const { minChartTimestamp, mostRecentLogTimestamp } = status ?? {};
-
-  return { from: minChartTimestamp, to: mostRecentLogTimestamp };
-};
-
```
Comment (joshxg) [inline src/features/Chart/ChartSlice.ts:131]: I removed the `minChartTimestamp` from the sensor status state and this is unused!

File: src/features/SensorStatus/SensorStatusManager.ts [hunk 3]
```diff
@@ -1,59 +1,79 @@
...
-        GROUP BY sensorid
-  
-      ) tb
-    ON tl.sensorid = tb.sensorid
-    GROUP BY tl.sensorid
-    order by timestamp
-  ) logs
-  ON logs.sensorid = s.id 
-  where s.id = ?
+enum SensorStatusQueryKey {
```
Comment (joshxg) [inline src/features/SensorStatus/SensorStatusManager.ts:4]: Keys for what is being returned from the query.. trying to keep them in sync. Maybe a better way to do this

File: src/features/SensorStatus/SensorStatusManager.ts [hunk 4]
```diff
@@ -1,59 +1,79 @@
...
+  [SensorStatusQueryKey.CurrentTemperature]: number;
+  [SensorStatusQueryKey.FirstTimestamp]: number;
+  [SensorStatusQueryKey.MostRecentLogTimestamp]: number;
+  [SensorStatusQueryKey.NumberOfColdBreaches]: number;
+  [SensorStatusQueryKey.NumberOfHotBreaches]: number;
+  [SensorStatusQueryKey.NumberOfLogs]: number;
+  [SensorStatusQueryKey.batteryLevel]: number;
+};
+
+const buildSensorStatusQuery = (whereClause = 'id = ?') => `
```
Comment (joshxg) [inline src/features/SensorStatus/SensorStatusManager.ts:24]: Tried to tidy this up. I am not sure right now about queries.

- Keep them in the same file is easier
- Keep them in a seperate file is a bit cleaner
- Keep them in a separate sql file is more cleaner (with syntax highlighting) but requires to read them in as a string 🤷

File: src/features/SensorStatus/SensorStatusManager.ts [hunk 5]
```diff
@@ -63,14 +83,27 @@ export class SensorStatusManager {
     this.databaseService = databaseService;
   }
 
+  mapStatusQueryResult = (result: SensorStatusQueryResult): SensorStatus => {
```
Comment (joshxg) [inline src/features/SensorStatus/SensorStatusManager.ts:86]: trying to be more explicit about the typing and safer with the values returned from the raw query

**Review by mark-prins — APPROVED** [review]
👍  That's very nice!
